name: Build and Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'   
        cache: 'npm'         

    - name: Install dependencies
      run: npm ci           

    - name: Build project
      run: |
        npm run build         # génère le dossier "dist"
        cp package.json dist/server/   # copie le package.json dans dist/server/ (pour npm install côté VPS)

    - name: Deploy to VPS via SCP
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}            
        username: ${{ secrets.USER }}        
        key: ${{ secrets.SSH_PRIVATE_KEY }}  
        port: 22011                          
        source: "dist/*"                     
        target: "/var/www/pratique/"              
        strip_components: 1                  
        rm: false                            
        overwrite: true                     
        debug: true                         

    - name: Install production dependencies on VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22011
        script: |
          cd /var/www/pratique/server
           npm ci
           npm install astro
           npm install send server-destroy
           PORT=8085 pm2 restart pratique || PORT=8085 pm2 start entry.mjs --name pratique